"""Add cover_image to Book model

Revision ID: 074d39a86a8a
Revises: bf53b8e9f1a2
Create Date: 2024-07-19 09:21:21.879078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074d39a86a8a'
down_revision = 'bf53b8e9f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
